/*

 CATHP.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char cathp[] =
{
  0x00,0x00,0x44,0x44,0xEE,0xAA,0xFE,0xBA,
  0xD6,0xFE,0xFE,0xEE,0x54,0x54,0x38,0x38,
  0x42,0x42,0x66,0x66,0x7E,0x7E,0xDB,0xFF,
  0xFF,0xDB,0xE7,0xE7,0x7E,0x7E,0x3C,0x3C
};

/* End of CATHP.C */
