/*

 FISH.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Fish[] =
{
  0x00,0x00,0x00,0x00,0x00,0x00,0x3A,0x3A,
  0x7F,0x45,0xDF,0xA1,0xFF,0x85,0x7A,0x7A,
  0x00,0x00,0x00,0x00,0x00,0x00,0x5C,0x5C,
  0xFE,0xA2,0xFB,0x85,0xFF,0xA1,0x5E,0x5E
};

/* End of FISH.C */
