/*

 YARN.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Yarn[] =
{
  0x02,0x00,0x05,0x38,0x29,0x54,0x34,0xCA,
  0x50,0xAE,0x64,0x9A,0x18,0x64,0x00,0x38,
  0x40,0x00,0xA0,0x1C,0x94,0x2A,0x2C,0x53,
  0x0A,0x75,0x26,0x59,0x18,0x26,0x00,0x1C
};

/* End of YARN.C */
